dist: bionic
language: generic
env:
  - TRAVIS_TAG=repository
  - TRAVIS_REPO_SLUG_L=$(echo "$TRAVIS_REPO_SLUG" | awk '{print tolower($0)}')
services:
  - docker
before_install:
  #- TRAVIS_REPO_SLUG_L=$(echo "$a" | awk '{print tolower($0)}') docker build -t $TRAVIS_REPO_SLUG_L .
  - echo "$TRAVIS_REPO_SLUG_L"
  - docker build -t $TRAVIS_REPO_SLUG_L .
  - docker run -d -t --name aurci $TRAVIS_REPO_SLUG_L bash
install:
  - docker cp pkgrepository.sh aurci:/home/pkguser
  - docker cp pkgbuild.sh aurci:/home/pkguser
  - if [ -f makepkg.conf ]; then
      docker cp makepkg.conf aurci:/home/pkguser/.makepkg.conf;
    fi
before_script:
  - docker cp pkglist aurci:/home/pkguser
  - docker cp pkgkeys aurci:/home/pkguser
script:
  - docker exec aurci bash pkgrepository.sh $TRAVIS_REPO_SLUG_L $TRAVIS_TAG
  - docker exec aurci bash pkgbuild.sh $TRAVIS_REPO_SLUG_L $TRAVIS_BUILD_ID
before_deploy:
  - docker cp aurci:/home/pkguser/bin $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ${TRAVIS_TAG}/*{db,files,gz,xz}
  overwrite: true
  skip_cleanup: true
  on:
    branch: $DEPLOY_BRANCH
